[theme]
# Primary accent color for interactive elements.
primaryColor = "#caebf2"

# Background color for the main content area.
backgroundColor = "#a9a9a9"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#ff3b3f"

# Color used for almost all text.
textColor = "#fafafa"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
